import type { ComplexStyleRule, CSSProperties } from "@vanilla-extract/css";
import type { ComponentPropsWithRef, ReactHTML } from "react";
import { colorProperties, responsiveProperties, Sprinkles } from "./sprinkles.css";
import * as vars from "./vars";

export type HTMLProps<T extends keyof ReactHTML> = Omit<ComponentPropsWithRef<T>, keyof Sprinkles>;

export type TuxedoComponentProps<T extends keyof ReactHTML> = HTMLProps<T> &
  Sprinkles &
  Omit<CSSProperties, keyof Sprinkles>;

export const styleProps = new Set(Object.keys({ ...colorProperties.styles, ...responsiveProperties.styles }));
export const styleValues = new Set([
  ...Object.keys({
    ...vars.radii,
    ...vars.space,
    ...vars.colors,
    ...vars.borderStyle,
  }),
  ...vars.alignItems,
  ...vars.display,
  ...vars.flexDirection,
  ...vars.justifyContent,
]);

export const isSprinkle = (prop: string, value: string) =>
  styleProps.has(prop) && (typeof value === "object" || styleValues.has(value));

export const isCSSValue = (prop: string): boolean => CSSStyles.has(prop);

export function splitStyleProps<T extends keyof ReactHTML>(
  props: TuxedoComponentProps<T>,
): [HTMLProps<T>, Sprinkles, ComplexStyleRule] {
  return Object.entries(props).reduce(
    (prev, curr) => {
      const [key, value] = curr;

      if (isSprinkle(key, value)) {
        return [
          prev[0],
          {
            ...prev[1],
            [key]: value,
          },
          prev[2],
        ];
      } else if (isCSSValue(key)) {
        return [
          prev[0],
          prev[1],
          {
            ...prev[2],
            [key]: value,
          },
        ];
      } else {
        return [
          {
            ...prev[0],
            [key]: value,
          },
          prev[1],
          prev[2],
        ];
      }
    },
    [{} as HTMLProps<T>, {} as Sprinkles, {} as ComplexStyleRule],
  );
}

export function mergeClassNames(...classList: Array<string | undefined>): string | undefined {
  const allClasses = classList.join(" ").trim();
  if (allClasses.length > 0) return allClasses;
  return undefined;
}

export const CSSStyles = new Set([
  "alignContent",
  "alignItems",
  "alignSelf",
  "all",
  "animation",
  "animationDelay",
  "animationDirection",
  "animationDuration",
  "animationFillMode",
  "animationIterationCount",
  "animationName",
  "animationPlayState",
  "animationTimingFunction",
  "backfaceVisibility",
  "background",
  "backgroundAttachment",
  "backgroundBlendMode",
  "backgroundClip",
  "backgroundColor",
  "backgroundImage",
  "backgroundOrigin",
  "backgroundPosition",
  "backgroundRepeat",
  "backgroundSize",
  "border",
  "borderBottom",
  "borderBottomColor",
  "borderBottomLeftRadius",
  "borderBottomRightRadius",
  "borderBottomStyle",
  "borderBottomWidth",
  "borderCollapse",
  "borderColor",
  "borderImage",
  "borderImageOutset",
  "borderImageRepeat",
  "borderImageSlice",
  "borderImageSource",
  "borderImageWidth",
  "borderLeft",
  "borderLeftColor",
  "borderLeftStyle",
  "borderLeftWidth",
  "borderRadius",
  "borderRight",
  "borderRightColor",
  "borderRightStyle",
  "borderRightWidth",
  "borderSpacing",
  "borderStyle",
  "borderTop",
  "borderTopColor",
  "borderTopLeftRadius",
  "borderTopRightRadius",
  "borderTopStyle",
  "borderTopWidth",
  "borderWidth",
  "bottom",
  "boxDecorationBreak",
  "boxShadow",
  "boxSizing",
  "breakAfter",
  "breakBefore",
  "breakInside",
  "captionSide",
  "caretColor",
  "@charset",
  "clear",
  "clip",
  "clipPath",
  "color",
  "columnCount",
  "columnFill",
  "columnGap",
  "columnRule",
  "columnRuleColor",
  "columnRuleStyle",
  "columnRuleWidth",
  "columnSpan",
  "columnWidth",
  "columns",
  "content",
  "counterIncrement",
  "counterReset",
  "cursor",
  "direction",
  "display",
  "emptyCells",
  "filter",
  "flex",
  "flexBasis",
  "flexDirection",
  "flexFlow",
  "flexGrow",
  "flexShrink",
  "flexWrap",
  "float",
  "font",
  "@fontFace",
  "fontFamily",
  "fontFeatureSettings",
  "fontKerning",
  "fontSize",
  "fontSizeAdjust",
  "fontStretch",
  "fontStyle",
  "fontVariant",
  "fontVariantCaps",
  "fontWeight",
  "gap",
  "grid",
  "gridArea",
  "gridAutoColumns",
  "gridAutoFlow",
  "gridAutoRows",
  "gridColumn",
  "gridColumnEnd",
  "gridColumnGap",
  "gridColumnStart",
  "gridGap",
  "gridRow",
  "gridRowEnd",
  "gridRowGap",
  "gridRowStart",
  "gridTemplate",
  "gridTemplateAreas",
  "gridTemplateColumns",
  "gridTemplateRows",
  "hangingPunctuation",
  "height",
  "hyphens",
  "@import",
  "isolation",
  "justifyContent",
  "@keyframes",
  "left",
  "letterSpacing",
  "lineHeight",
  "listStyle",
  "listStyleImage",
  "listStylePosition",
  "listStyleType",
  "margin",
  "marginBottom",
  "marginLeft",
  "marginRight",
  "marginTop",
  "maxHeight",
  "maxWidth",
  "@media",
  "minHeight",
  "minWidth",
  "mixBlendMode",
  "objectFit",
  "objectPosition",
  "opacity",
  "order",
  "outline",
  "outlineColor",
  "outlineOffset",
  "outlineStyle",
  "outlineWidth",
  "overflow",
  "overflowX",
  "overflowY",
  "padding",
  "paddingBottom",
  "paddingLeft",
  "paddingRight",
  "paddingTop",
  "pageBreakAfter",
  "pageBreakBefore",
  "pageBreakInside",
  "perspective",
  "perspectiveOrigin",
  "pointerEvents",
  "position",
  "quotes",
  "resize",
  "right",
  "rowGap",
  "scrollBehavior",
  "tabSize",
  "tableLayout",
  "textAlign",
  "textAlignLast",
  "textDecoration",
  "textDecorationColor",
  "textDecorationLine",
  "textDecorationStyle",
  "textIndent",
  "textJustify",
  "textOverflow",
  "textShadow",
  "textTransform",
  "top",
  "transform",
  "transformOrigin",
  "transformStyle",
  "transition",
  "transitionDelay",
  "transitionDuration",
  "transitionProperty",
  "transitionTimingFunction",
  "unicodeBidi",
  "userSelect",
  "verticalAlign",
  "visibility",
  "whiteSpace",
  "width",
  "wordBreak",
  "wordSpacing",
  "wordWrap",
  "writingMode",
  "zIndex",
]);
