import { CSSProperties } from "react";
import theme from "../styles/theme";

// Emotion takes care of the cross-browser support, so only base properties are needed here.
const CSSStyles: Array<string> = [
  "alignContent",
  "alignItems",
  "alignSelf",
  "animation",
  "animationDelay",
  "animationDirection",
  "animationDuration",
  "animationFillMode",
  "animationIterationCount",
  "animationName",
  "animationPlayState",
  "animationTimingFunction",
  "backfaceVisibility",
  "background",
  "backgroundAttachment",
  "backgroundClip",
  "backgroundColor",
  "backgroundImage",
  "backgroundOrigin",
  "backgroundPosition",
  "backgroundRepeat",
  "backgroundSize",
  "border",
  "borderBottom",
  "borderBottomColor",
  "borderBottomLeftRadius",
  "borderBottomRightRadius",
  "borderBottomStyle",
  "borderBottomWidth",
  "borderCollapse",
  "borderColor",
  "borderImage",
  "borderImageOutset",
  "borderImageRepeat",
  "borderImageSlice",
  "borderImageSource",
  "borderImageWidth",
  "borderLeft",
  "borderLeftColor",
  "borderLeftStyle",
  "borderLeftWidth",
  "borderRadius",
  "borderRight",
  "borderRightColor",
  "borderRightStyle",
  "borderRightWidth",
  "borderSpacing",
  "borderStyle",
  "borderTop",
  "borderTopColor",
  "borderTopLeftRadius",
  "borderTopRightRadius",
  "borderTopStyle",
  "borderTopWidth",
  "borderWidth",
  "bottom",
  "boxShadow",
  "boxSizing",
  "captionSide",
  "clear",
  "clip",
  "color",
  "columnCount",
  "columnFill",
  "columnGap",
  "columnRule",
  "columnRuleColor",
  "columnRuleStyle",
  "columnRuleWidth",
  "columnSpan",
  "columnWidth",
  "columns",
  "content",
  "counterIncrement",
  "counterReset",
  "cursor",
  "direction",
  "display",
  "emptyCells",
  "flex",
  "flexBasis",
  "flexDirection",
  "flexFlow",
  "flexGrow",
  "flexShrink",
  "flexWrap",
  "float",
  "font",
  "fontFamily",
  "fontSize",
  "fontSizeAdjust",
  "fontStretch",
  "fontStyle",
  "fontVariant",
  "fontWeight",
  "gap",
  "height",
  "justifyContent",
  "left",
  "letterSpacing",
  "lineHeight",
  "listStyle",
  "listStyleImage",
  "listStylePosition",
  "listStyleType",
  "margin",
  "marginBottom",
  "marginLeft",
  "marginRight",
  "marginTop",
  "maxHeight",
  "maxWidth",
  "minHeight",
  "minWidth",
  "opacity",
  "order",
  "outline",
  "outlineColor",
  "outlineOffset",
  "outlineStyle",
  "outlineWidth",
  "overflow",
  "overflowX",
  "overflowY",
  "padding",
  "paddingBottom",
  "paddingLeft",
  "paddingRight",
  "paddingTop",
  "pageBreakAfter",
  "pageBreakBefore",
  "pageBreakInside",
  "perspective",
  "perspectiveOrigin",
  "position",
  "quotes",
  "resize",
  "right",
  "tabSize",
  "tableLayout",
  "textAlign",
  "textAlignLast",
  "textDecoration",
  "textDecorationColor",
  "textDecorationLine",
  "textDecorationStyle",
  "textIndent",
  "textJustify",
  "textOverflow",
  "textShadow",
  "textTransform",
  "top",
  "transform",
  "transformOrigin",
  "transformStyle",
  "transition",
  "transitionDelay",
  "transitionDuration",
  "transitionProperty",
  "transitionTimingFunction",
  "verticalAlign",
  "visibility",
  "whiteSpace",
  "width",
  "wordBreak",
  "wordSpacing",
  "wordWrap",
  "zIndex",
];

/**
 * This function takes the key of a prop and returns whether that key is a valid CSS property.
 * @param prop The key of the prop to test.
 * @returns Whether the key passed in is a valid CSS property.
 */
export const isValidCssProp = (prop: string): prop is keyof CSSProperties => CSSStyles.includes(prop);

/**
 * This function takes an object of props that has a mix of HTML attributes, custom component props, and CSS styles and
 * returns an object of just the CSS properties. Any CSS properties passed in as numbers will be evalutated using the
 * spacing function provided in the Theme object.
 * @param props The props passed to the element to separate the CSSProperties from.
 * @returns An object with just the CSSProperties from the props.
 */
export const extractCssFromProps = (props: { [x: string]: any }): CSSProperties => {
  const propKeys = Object.keys(props);
  const validStyleKeys = propKeys.filter((key) => isValidCssProp(key));

  const styleProps: { [x: string]: any } = {};

  validStyleKeys.forEach((styleKey) => {
    const key = styleKey as keyof CSSProperties;

    // auto evaluate numbers using the spacing function from the Theme object
    styleProps[key] = isNaN(+props[styleKey]) ? props[styleKey] : theme.spacing(props[styleKey]);
  });
  return styleProps;
};
